// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  technicalDocumentation: [
    {
      type: 'category',
      label: 'Documentation',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Docs',
        },
      ],
    },
  ],
};

export default sidebars;